# Generated by Django 5.2.4 on 2025-08-14 15:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Belt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Пояс', max_length=50, verbose_name='Пояс')),
            ],
        ),
        migrations.CreateModel(
            name='Complex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Наименование', max_length=100, verbose_name='Наименование')),
                ('points', models.SmallIntegerField(default=0, help_text='Балл', verbose_name='Балл')),
            ],
        ),
        migrations.CreateModel(
            name='ComplexGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Наименование', max_length=100, verbose_name='Наименование')),
            ],
        ),
        migrations.CreateModel(
            name='BeltDemand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('belt', models.ForeignKey(help_text='Пояс', on_delete=django.db.models.deletion.PROTECT, to='attestation.belt', verbose_name='Пояс')),
                ('complex', models.ForeignKey(help_text='Комплекс', on_delete=django.db.models.deletion.CASCADE, to='attestation.complex', verbose_name='Комплекс')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Наименование', max_length=100, verbose_name='Наименование')),
                ('year_start', models.SmallIntegerField(help_text='Год рождения начальный', verbose_name='Год рождения начальный')),
                ('year_end', models.SmallIntegerField(help_text='Год рождения конечный', verbose_name='Год рождения конечный')),
                ('belt_attestation', models.ForeignKey(help_text='Пояс аттестационный', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='attestation.belt', verbose_name='Пояс аттестационный')),
                ('belt_end', models.ForeignKey(help_text='Пояс конечный', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='attestation.belt', verbose_name='Пояс конечный')),
                ('belt_start', models.ForeignKey(help_text='Пояс начальный', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='attestation.belt', verbose_name='Пояс начальный')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Наименование', max_length=100, verbose_name='Наименование')),
                ('value', models.CharField(help_text='Значение', max_length=100, verbose_name='Значение')),
                ('user', models.ForeignKey(help_text='Пользователь', on_delete=django.db.models.deletion.CASCADE, related_name='options', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(help_text='Фамилия', max_length=50, verbose_name='Фамилия')),
                ('name', models.CharField(help_text='Имя', max_length=30, verbose_name='Имя')),
                ('patronymic', models.CharField(help_text='Отчество', max_length=50, verbose_name='Отчество')),
                ('birth_date', models.DateField(help_text='Дата рождения', verbose_name='Дата рождения')),
                ('belt', models.ForeignKey(help_text='Пояс', on_delete=django.db.models.deletion.PROTECT, related_name='participants', to='attestation.belt', verbose_name='Пояс')),
            ],
        ),
        migrations.CreateModel(
            name='Attestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.SmallIntegerField(help_text='Балл', verbose_name='Балл')),
                ('judge', models.ForeignKey(help_text='Судья', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Судья')),
                ('complex', models.ForeignKey(help_text='Комплекс', on_delete=django.db.models.deletion.CASCADE, to='attestation.complex', verbose_name='Комплекс')),
                ('participant', models.ForeignKey(help_text='Участник', on_delete=django.db.models.deletion.CASCADE, to='attestation.participant', verbose_name='Участник')),
            ],
        ),
    ]
