# Generated by Django 5.2.4 on 2025-08-14 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attestation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attestation',
            name='complex',
            field=models.ForeignKey(help_text='Комплекс', on_delete=django.db.models.deletion.CASCADE, related_name='attestations', to='attestation.complex', verbose_name='Комплекс'),
        ),
        migrations.AlterField(
            model_name='attestation',
            name='participant',
            field=models.ForeignKey(help_text='Участник', on_delete=django.db.models.deletion.CASCADE, related_name='attestations', to='attestation.participant', verbose_name='Участник'),
        ),
    ]
