# Generated by Django 5.2.4 on 2025-08-14 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attestation', '0003_alter_option_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='complex',
            name='complex_group',
            field=models.ForeignKey(default=1, help_text='Группа комплекса', on_delete=django.db.models.deletion.CASCADE, related_name='complexes', to='attestation.complexgroup', verbose_name='Группа комплекса'),
            preserve_default=False,
        ),
    ]
