# Generated by Django 5.2.4 on 2025-08-21 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attestation', '0004_complex_complex_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beltdemand',
            name='belt',
            field=models.ForeignKey(help_text='Пояс', on_delete=django.db.models.deletion.CASCADE, to='attestation.belt', verbose_name='Пояс'),
        ),
        migrations.CreateModel(
            name='ParticipantGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(help_text='Группа', on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='attestation.group', verbose_name='Группа')),
                ('participant', models.ForeignKey(help_text='Участник', on_delete=django.db.models.deletion.CASCADE, related_name='participant_group', to='attestation.participant', verbose_name='Участник')),
            ],
        ),
    ]
