# Generated by Django 5.2.4 on 2025-08-31 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attestation', '0005_alter_beltdemand_belt_participantgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='complexgroup',
            name='status',
            field=models.CharField(default='Ожидание', help_text='Статус аттестации', max_length=30, verbose_name='Статус аттестации'),
        ),
    ]
