# Generated by Django 5.2.4 on 2025-08-31 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attestation', '0006_complexgroup_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complexgroup',
            name='status',
        ),
        migrations.AddField(
            model_name='group',
            name='status',
            field=models.CharField(default='Ожидание', help_text='Статус аттестации', max_length=30, verbose_name='Статус аттестации'),
        ),
    ]
