# Generated by Django 5.2.4 on 2025-08-31 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attestation', '0007_remove_complexgroup_status_group_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='attestation',
            name='order',
            field=models.SmallIntegerField(default=1, help_text='Порядок участников', verbose_name='Порядок участников'),
        ),
    ]
