# Generated by Django 5.2.4 on 2025-08-31 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attestation', '0008_attestation_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attestation',
            name='order',
        ),
        migrations.AddField(
            model_name='participantgroup',
            name='order',
            field=models.SmallIntegerField(default=1, help_text='Порядок участников', verbose_name='Порядок участников'),
        ),
    ]
