# Generated by Django 5.2.4 on 2025-09-02 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attestation', '0009_remove_attestation_order_participantgroup_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attestation',
            old_name='point',
            new_name='points',
        ),
    ]
