# Generated by Django 5.2.4 on 2025-09-18 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attestation', '0010_rename_point_attestation_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='user',
        ),
    ]
