# Generated by Django 5.2.4 on 2025-09-23 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attestation', '0011_remove_option_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='value',
            field=models.CharField(default='', help_text='Значение', max_length=100, verbose_name='Значение'),
        ),
    ]
