# Generated by Django 5.2.4 on 2025-09-28 12:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attestation', '0012_alter_option_value'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Наименование', max_length=100, verbose_name='Наименование')),
            ],
        ),
        migrations.CreateModel(
            name='PhysicalTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Наименование', max_length=100, verbose_name='Наименование')),
            ],
        ),
        migrations.AlterField(
            model_name='group',
            name='status',
            field=models.CharField(choices=[('Ожидание', 'Ожидание'), ('В процессе', 'В процессе'), ('Завершено', 'Завершено')], default='Ожидание', help_text='Статус аттестации', max_length=30, verbose_name='Статус аттестации'),
        ),
        migrations.CreateModel(
            name='AdditionalTestCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Наименование', max_length=100, verbose_name='Наименование')),
                ('additional_test', models.ForeignKey(help_text='Дополнительный тест', on_delete=django.db.models.deletion.CASCADE, to='attestation.additionaltest', verbose_name='Дополнительный тест')),
            ],
        ),
        migrations.CreateModel(
            name='AdditionalAttestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judge', models.ForeignKey(help_text='Судья', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Судья')),
                ('participant', models.ForeignKey(help_text='Участник', on_delete=django.db.models.deletion.CASCADE, related_name='additional_attestations', to='attestation.participant', verbose_name='Участник')),
                ('complex', models.ForeignKey(help_text='Комплекс', on_delete=django.db.models.deletion.CASCADE, related_name='additional_attestations', to='attestation.additionaltest', verbose_name='Комплекс')),
                ('criteria', models.ForeignKey(help_text='Выполненный критерий', on_delete=django.db.models.deletion.CASCADE, to='attestation.additionaltestcriteria', verbose_name='Выполненный критерий')),
            ],
        ),
        migrations.CreateModel(
            name='AdditionalTestDemands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.SmallIntegerField(default=0, help_text='Балл', verbose_name='Балл')),
                ('belt', models.ForeignKey(help_text='Пояс', on_delete=django.db.models.deletion.CASCADE, to='attestation.belt', verbose_name='Пояс')),
                ('criteria', models.ForeignKey(help_text='Критерий', on_delete=django.db.models.deletion.CASCADE, to='attestation.additionaltestcriteria', verbose_name='Критерий')),
            ],
        ),
        migrations.CreateModel(
            name='PhysicalAttestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.SmallIntegerField(help_text='Балл', verbose_name='Балл')),
                ('judge', models.ForeignKey(help_text='Судья', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Судья')),
                ('participant', models.ForeignKey(help_text='Участник', on_delete=django.db.models.deletion.CASCADE, related_name='physical_attestations', to='attestation.participant', verbose_name='Участник')),
                ('complex', models.ForeignKey(help_text='Комплекс', on_delete=django.db.models.deletion.CASCADE, related_name='physical_attestations', to='attestation.physicaltest', verbose_name='Комплекс')),
            ],
        ),
        migrations.CreateModel(
            name='PhysicalTestDemand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criteria', models.SmallIntegerField(default=0, help_text='Критерий', verbose_name='Критерий')),
                ('points', models.SmallIntegerField(default=0, help_text='Балл', verbose_name='Балл')),
                ('belt', models.ForeignKey(help_text='Пояс', on_delete=django.db.models.deletion.CASCADE, to='attestation.belt', verbose_name='Пояс')),
                ('test', models.ForeignKey(help_text='Физический комплекс', on_delete=django.db.models.deletion.CASCADE, to='attestation.physicaltest', verbose_name='Физический комплекс')),
            ],
        ),
    ]
