# Generated by Django 5.2.4 on 2025-10-01 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attestation', '0013_additionaltest_physicaltest_alter_group_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additionaltestdemands',
            name='points',
        ),
        migrations.AddField(
            model_name='additionaltestcriteria',
            name='points',
            field=models.SmallIntegerField(default=0, help_text='Балл', verbose_name='Балл'),
        ),
        migrations.AlterField(
            model_name='additionaltestcriteria',
            name='additional_test',
            field=models.ForeignKey(help_text='Дополнительный тест', on_delete=django.db.models.deletion.CASCADE, related_name='criterias', to='attestation.additionaltest', verbose_name='Дополнительный тест'),
        ),
    ]
