# Generated by Django 5.2.4 on 2025-10-19 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attestation', '0014_remove_additionaltestdemands_points_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdditionalTestDemands',
            new_name='AdditionalTestDemand',
        ),
    ]
