# Generated by Django 5.2.4 on 2025-10-25 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attestation', '0015_rename_additionaltestdemands_additionaltestdemand'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhysicalTestPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.SmallIntegerField(default=0, help_text='Процент', verbose_name='Процент')),
                ('points', models.SmallIntegerField(default=0, help_text='Балл', verbose_name='Балл')),
            ],
        ),
        migrations.RemoveField(
            model_name='physicaltestdemand',
            name='points',
        ),
    ]
