# Generated by Django 5.2.4 on 2025-10-26 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attestation', '0016_physicaltestpoint_remove_physicaltestdemand_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attestation',
            name='points',
            field=models.FloatField(help_text='Балл', verbose_name='Балл'),
        ),
    ]
