# Generated by Django 5.2.4 on 2025-11-02 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attestation', '0017_alter_attestation_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additionalattestation',
            name='judge',
        ),
        migrations.RemoveField(
            model_name='physicalattestation',
            name='judge',
        ),
    ]
