# Generated by Django 5.2.4 on 2025-11-02 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attestation', '0018_remove_additionalattestation_judge_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='physicalattestation',
            old_name='complex',
            new_name='test',
        ),
    ]
