# Generated by Django 5.2.4 on 2025-11-03 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attestation', '0019_rename_complex_physicalattestation_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='additionalattestation',
            old_name='complex',
            new_name='test',
        ),
    ]
