# Generated by Django 5.2.4 on 2025-11-03 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attestation', '0020_rename_complex_additionalattestation_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additionalattestation',
            name='test',
        ),
    ]
