# Generated by Django 5.2.4 on 2025-11-03 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attestation', '0021_remove_additionalattestation_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalattestation',
            name='test',
            field=models.ForeignKey(default=None, help_text='Выполненный тест', on_delete=django.db.models.deletion.CASCADE, to='attestation.additionaltest', verbose_name='Выполненный тест'),
            preserve_default=False,
        ),
    ]
