# Generated by Django 5.2.4 on 2025-11-08 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attestation', '0022_additionalattestation_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttestationInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complex', models.ForeignKey(help_text='Комплекс', on_delete=django.db.models.deletion.CASCADE, to='attestation.complex', verbose_name='Комплекс')),
                ('complex_group', models.ForeignKey(help_text='Группа комплекса', on_delete=django.db.models.deletion.CASCADE, to='attestation.complexgroup', verbose_name='Группа комплекса')),
                ('group', models.ForeignKey(help_text='Группа', on_delete=django.db.models.deletion.CASCADE, to='attestation.group', verbose_name='Группа')),
            ],
        ),
    ]
