# Generated by Django 5.2.4 on 2025-11-30 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attestation', '0023_attestationinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgePeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_from', models.SmallIntegerField(help_text='Возраст от', verbose_name='Возраст от')),
                ('age_to', models.SmallIntegerField(help_text='Возраст до', verbose_name='Возраст до')),
            ],
        ),
        migrations.AddField(
            model_name='physicaltestdemand',
            name='age_period',
            field=models.ForeignKey(default=1, help_text='Возраста', on_delete=django.db.models.deletion.CASCADE, to='attestation.ageperiod', verbose_name='Возраста'),
            preserve_default=False,
        ),
    ]
