# Generated by Django 5.2.4 on 2025-11-30 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attestation', '0024_ageperiod_physicaltestdemand_age_period'),
    ]

    operations = [
        migrations.RenameField(
            model_name='physicaltestdemand',
            old_name='criteria',
            new_name='criteria_female',
        ),
        migrations.AddField(
            model_name='physicaltestdemand',
            name='criteria_male',
            field=models.SmallIntegerField(default=0, help_text='Критерий', verbose_name='Критерий'),
        ),
    ]
