# Generated by Django 5.2.4 on 2025-12-05 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attestation', '0025_rename_criteria_physicaltestdemand_criteria_female_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='sex',
            field=models.CharField(choices=[('М', 'm'), ('Ж', 'f')], default='m', help_text='Пол', max_length=1, verbose_name='Пол'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='physicaltestdemand',
            name='criteria_female',
            field=models.SmallIntegerField(default=0, help_text='Критерий для женщин', verbose_name='Критерий для женщин'),
        ),
        migrations.AlterField(
            model_name='physicaltestdemand',
            name='criteria_male',
            field=models.SmallIntegerField(default=0, help_text='Критерий для мужчин', verbose_name='Критерий для мужчин'),
        ),
    ]
