# Generated by Django 5.2.4 on 2025-12-07 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attestation', '0026_participant_sex_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='sex',
            field=models.CharField(choices=[('м', 'м'), ('ж', 'ж')], default='м', help_text='Пол', max_length=1, verbose_name='Пол'),
        ),
    ]
