# Generated by Django 5.2.4 on 2026-01-01 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attestation', '0027_alter_participant_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complex',
            name='points',
            field=models.SmallIntegerField(default=5, help_text='Балл', verbose_name='Балл'),
        ),
    ]
