# Generated by Django 5.2.4 on 2025-08-14 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_judging',
            field=models.BooleanField(default=False, help_text='Аттестует', verbose_name='Аттестует'),
        ),
    ]
